CHG: Add script options

diff --git a/bin/aws-ssm b/bin/aws-ssm
--- a/bin/aws-ssm
+++ b/bin/aws-ssm
@@ -15,6 +15,31 @@ if ! command -v fzf &> /dev/null; then
   exit 1
 fi
 
+function usage() {
+  echo "Usage: $0 [profile] [instance]" >&2
+}
+
+while getopts ":h" opt; do
+  case $opt in
+    h)
+      usage
+      exit 0
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      usage
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      usage
+      exit 1
+      ;;
+  esac
+done
+
+shift $((OPTIND - 1))
+
 PROFILE=$1
 
 if [[ -z $PROFILE ]]; then
@@ -30,6 +55,7 @@ fi
 
 if [[ -z $PROFILE ]]; then
   echo "No profile selected"
+  usage
   exit 1
 fi
 
@@ -48,6 +74,7 @@ fi
 
 if [[ -z $SELECTED ]]; then
   echo "No instance selected"
+  usage
   exit 1
 fi
 
@@ -55,6 +82,7 @@ INSTANCE_ID=${INSTANCES[$SELECTED]}
 
 if [[ -z $INSTANCE_ID ]]; then
   echo "No instance found for $SELECTED"
+  usage
   exit 1
 fi
 
